name: Tests

on: [push, pull_request]

jobs:
  tests:
    name: Tests PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.0]
        include:
          - php: 8.0
            analysis: true

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Conding standard
        if: matrix.analysis
        run: vendor/bin/phpcs

      - name: Static analysis
        if: matrix.analysis
        run: vendor/bin/phpstan analyse

      - name: Tests
        run: vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml --coverage-xml=build/coverage/coverage-xml --log-junit=build/coverage/junit.xml

      - name: Infection
        run: vendor/bin/infection -s --threads=4 --coverage=build/coverage --logger-github -v

      - name: Upload coverage results to Coveralls
        if: matrix.analysis
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          composer require --dev php-coveralls/php-coveralls --no-progress --prefer-dist --optimize-autoloader
          vendor/bin/php-coveralls -v
